// <auto-generated />
namespace StarterTest.BL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class dbMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202009121147525_dbMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
